# Generated by Django 4.2.5 on 2023-09-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_comment='minutes precision')),
                ('duration', models.PositiveIntegerField(db_comment='in minutes')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.car')),
            ],
        ),
    ]
